name: app_tournament
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.4
  crypto: ^3.0.1
  google_fonts: ^2.3.1
  provider: ^6.0.2
  rxdart: ^0.27.3
  json_annotation: ^4.4.0
  cached_network_image: ^3.2.1
  ionicons: ^0.1.2
  font_awesome_flutter: ^9.2.0
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^1.0.3 
  firebase_messaging: ^11.2.6 
  clipboard: ^0.1.3
  shimmer: ^2.0.0 
  hive: ^2.0.5
  path_provider: ^2.0.9
  lottie: ^1.2.2
  flutter_local_notifications: ^9.4.0
  razorpay_flutter: ^1.2.9
  # intl_phone_number_input: ^0.7.0+2
  country_picker: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0 
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  
flutter:

  uses-material-design: true
  
  assets:
    - assets/ 
    
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages